# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: STO_tests_V2_nanopb.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19STO_tests_V2_nanopb.proto\x1a\x0cnanopb.proto\"R\n\x07Message\x12\x1d\n\x08testData\x18\x01 \x01(\x0b\x32\t.TestDataH\x00\x12#\n\x0bmcuSettings\x18\x02 \x01(\x0b\x32\x0c.MCUSettingsH\x00\x42\x03\n\x01s\"\x82\x01\n\x0bMCUSettings\x12\x17\n\x06method\x18\x01 \x02(\x0e\x32\x07.Method\x12\x12\n\x03uid\x18\x02 \x01(\tB\x05\x92?\x02p\x0c\x12\x17\n\x0f\x66irmwareVersion\x18\x03 \x01(\r\x12\x17\n\x0fprotobufVersion\x18\x04 \x01(\r\x12\x14\n\x0crtcTimestamp\x18\x05 \x01(\r\"\x8f\x03\n\x08TestData\x12\x17\n\x06method\x18\x01 \x02(\x0e\x32\x07.Method\x12\x12\n\ntestNumber\x18\x02 \x02(\r\x12\x0f\n\x07timeout\x18\x03 \x01(\r\x12\x15\n\raccDataNumber\x18\x04 \x01(\r\x12\x12\n\nAIRBAG_OFF\x18\x05 \x01(\x08\x12$\n\x11Seatbelt_position\x18\x06 \x01(\x0e\x32\t.Position\x12\x15\n\rvehicle_speed\x18\x07 \x01(\r\x12\x0f\n\x07mileage\x18\x08 \x01(\r\x12\x1c\n\x14VehicleStateExtended\x18\t \x01(\x08\x12\x15\n\rGenDiagEnable\x18\n \x01(\r\x12 \n\rDoor_position\x18\x0b \x01(\x0e\x32\t.Position\x12\x13\n\x0bUDS_subtest\x18\x0c \x01(\r\x12\x0f\n\x07UDS_NRC\x18\r \x01(\r\x12\x10\n\x08UDS_snap\x18\x0e \x01(\r\x12\x1c\n\rmeasuredValue\x18\x0f \x03(\x01\x42\x05\x92?\x02\x10\n\x12\x1f\n\x05\x66rame\x18\x10 \x03(\x0b\x32\t.CanFrameB\x05\x92?\x02\x10(\"N\n\x08\x43\x61nFrame\x12\x11\n\ttimestamp\x18\x01 \x02(\r\x12\n\n\x02id\x18\x02 \x02(\r\x12\x0e\n\x06length\x18\x03 \x02(\r\x12\x13\n\x04\x64\x61ta\x18\x04 \x02(\x0c\x42\x05\x92?\x02\x08\x08*\x1a\n\x06Method\x12\x07\n\x03SET\x10\x00\x12\x07\n\x03GET\x10\x01*\x87\x01\n\x08Position\x12\x0f\n\x0bNot_Tracked\x10\x00\x12\n\n\x06\x44river\x10\x01\x12\x13\n\x0f\x46ront_passenger\x10\x02\x12\x17\n\x13Rear_passengerRight\x10\x03\x12\x18\n\x14Rear_passengerCenter\x10\x04\x12\x16\n\x12Rear_passengerLeft\x10\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'STO_tests_V2_nanopb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MCUSETTINGS'].fields_by_name['uid']._loaded_options = None
  _globals['_MCUSETTINGS'].fields_by_name['uid']._serialized_options = b'\222?\002p\014'
  _globals['_TESTDATA'].fields_by_name['measuredValue']._loaded_options = None
  _globals['_TESTDATA'].fields_by_name['measuredValue']._serialized_options = b'\222?\002\020\n'
  _globals['_TESTDATA'].fields_by_name['frame']._loaded_options = None
  _globals['_TESTDATA'].fields_by_name['frame']._serialized_options = b'\222?\002\020('
  _globals['_CANFRAME'].fields_by_name['data']._loaded_options = None
  _globals['_CANFRAME'].fields_by_name['data']._serialized_options = b'\222?\002\010\010'
  _globals['_METHOD']._serialized_start=742
  _globals['_METHOD']._serialized_end=768
  _globals['_POSITION']._serialized_start=771
  _globals['_POSITION']._serialized_end=906
  _globals['_MESSAGE']._serialized_start=43
  _globals['_MESSAGE']._serialized_end=125
  _globals['_MCUSETTINGS']._serialized_start=128
  _globals['_MCUSETTINGS']._serialized_end=258
  _globals['_TESTDATA']._serialized_start=261
  _globals['_TESTDATA']._serialized_end=660
  _globals['_CANFRAME']._serialized_start=662
  _globals['_CANFRAME']._serialized_end=740
# @@protoc_insertion_point(module_scope)
