# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets,QtSerialPort
from handlers import Messages
import threading
class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 60, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 130, 481, 271))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.UART = QtSerialPort.QSerialPort("COM5", baudRate=QtSerialPort.QSerialPort.Baud115200)
        self.pushButton.clicked.connect(self.Test4_thread) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "СТО БУ СНБП АВТОВАЗ"))
        self.pushButton.setText(_translate("MainWindow", "Начать"))
    def foo(self):
        print("111")
        self.textBrowser.append("Запуск теста 4")
    def Test4_run(self):
        Command = Messages.TestData()
        Result = Messages.TestData()
        Command.method = 0
        Command.testNumber = 4
        Command.Seatbelt_position = 1
        Command.VehicleStateExtended = 1
        Command = Command.SerializeToString()
        self.UART.write(Command)
        self.textBrowser.append("Запуск теста 4")
        while (self.UART.canReadLine):
            bytes_read = self.UART.readLine()
        self.textBrowser.append('HUI')
        print(bytes_read)
        self.textBrowser.append(str(bytes_read))
        Result.ParseFromString(bytes_read)
        print(Result)
        self.textBrowser.append(Result)
    def Test4_thread(self):
        Receiver=threading.Thread(target=self.Test4_run)
        Receiver.start()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
